language: python
python:
  - "2.6"
  - "2.7"
before_install:
- export PIP_USE_MIRRORS=true
install:
  - pip install -e .
  - pip install -r requirements.txt
  - pip install coveralls
  - ./download_test_data.sh
script: nosetests --with-coverage --cover-package=pdftables
after_success:
  - coveralls
